# Generated by Django 3.1 on 2021-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210413_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
