# Generated by Django 3.1 on 2021-05-04 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('product_type', models.CharField(choices=[('all', 'All'), ('protein', 'Protein'), ('vitamins', 'Vitamins'), ('supplements', 'Supplements'), ('equipment', 'Equipment')], max_length=11)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
